const VOYAGES = [
    {
        id: 'black-pearl',
        name: 'The Black Pearl',
        image: 'https://placehold.co/400x300/1a1410/ffd700?text=Black+Pearl',
        price: '500 pieces of eight',
        priceValue: 500,
        speed: 'Fastest',
        speedValue: 10,
        safety: 'Cursed',
        safetyValue: 3,
        captain: 'Captain Jack Sparrow',
        description: 'The fastest ship in the Caribbean... when she\'s running',
        capacity: 50,
        type: 'fastest',
        quote: '"Not all treasure is silver and gold, mate"'
    },
    {
        id: 'flying-dutchman',
        name: 'The Flying Dutchman',
        image: 'https://placehold.co/400x300/0a3d2e/4ade80?text=Flying+Dutchman',
        price: '666 souls',
        priceValue: 666,
        speed: 'Supernatural',
        speedValue: 9,
        safety: 'Haunted',
        safetyValue: 2,
        captain: 'Davy Jones',
        description: 'She can sail beneath the waves',
        capacity: 80,
        type: 'fastest',
        quote: '"Do you fear death?"'
    },
    {
        id: 'queen-annes-revenge',
        name: "Queen Anne's Revenge",
        image: 'https://placehold.co/400x300/8a0303/ffd700?text=Queen+Annes+Revenge',
        price: '750 pieces of eight',
        priceValue: 750,
        speed: 'Swift',
        speedValue: 7,
        safety: 'Dangerous',
        safetyValue: 4,
        captain: 'Blackbeard',
        description: 'Fear the man with the burning beard',
        capacity: 100,
        type: 'safest',
        quote: '"Some men be born handsome, others do not be"'
    },
    {
        id: 'silent-mary',
        name: 'The Silent Mary',
        image: 'https://placehold.co/400x300/2d1a16/8b4513?text=Silent+Mary',
        price: '400 pieces of eight',
        priceValue: 400,
        speed: 'Vengeful',
        speedValue: 8,
        safety: 'Deadly',
        safetyValue: 1,
        captain: 'Captain Salazar',
        description: 'The Triangle is her hunting ground',
        capacity: 60,
        type: 'cheapest',
        quote: '"No pirates will survive!"'
    },
    {
        id: 'interceptor',
        name: 'HMS Interceptor',
        image: 'https://placehold.co/400x300/1e3a5f/ffffff?text=HMS+Interceptor',
        price: '350 pieces of eight',
        priceValue: 350,
        speed: 'Quick',
        speedValue: 8,
        safety: 'Moderately Safe',
        safetyValue: 7,
        captain: 'James Norrington',
        description: 'A fine ship, and fast',
        capacity: 40,
        type: 'cheapest',
        quote: '"One good deed is not enough to redeem a man"'
    },
    {
        id: 'empress',
        name: 'The Empress',
        image: 'https://placehold.co/400x300/8b0000/ffd700?text=The+Empress',
        price: '600 pieces of eight',
        priceValue: 600,
        speed: 'Steady',
        speedValue: 6,
        safety: 'Well-Armed',
        safetyValue: 8,
        captain: 'Sao Feng',
        description: 'Singapore\'s finest vessel',
        capacity: 70,
        type: 'safest',
        quote: '"Welcome to Singapore"'
    },
    {
        id: 'wicked-wench',
        name: 'The Wicked Wench',
        image: 'https://placehold.co/400x300/d97706/fef3c7?text=Wicked+Wench',
        price: '300 pieces of eight',
        priceValue: 300,
        speed: 'Leisurely',
        speedValue: 5,
        safety: 'Safest',
        safetyValue: 9,
        captain: 'Young Jack Sparrow',
        description: 'Before she became the Pearl...',
        capacity: 35,
        type: 'safest',
        quote: '"A touch of destiny"'
    },
    {
        id: 'providence',
        name: 'The Providence',
        image: 'https://placehold.co/400x300/0f766e/ccfbf1?text=The+Providence',
        price: '250 pieces of eight',
        priceValue: 250,
        speed: 'Slow but Steady',
        speedValue: 4,
        safety: 'Very Safe',
        safetyValue: 10,
        captain: 'Captain Teague',
        description: 'For those who value arriving alive',
        capacity: 45,
        type: 'cheapest',
        quote: '"Keep to the Code"'
    },
    {
        id: 'dying-gull',
        name: 'The Dying Gull',
        image: 'https://placehold.co/400x300/57534e/a8a29e?text=Dying+Gull',
        price: '50 pieces of eight',
        priceValue: 50,
        speed: 'Pathetic',
        speedValue: 2,
        safety: 'Questionable',
        safetyValue: 5,
        captain: 'Captain Jack Sparrow',
        description: 'She\'s... a boat',
        capacity: 10,
        type: 'cheapest',
        quote: '"I have a ship!"'
    }
];

const SEAT_TOOLTIPS = [
    "Smells like rum and regret",
    "Previous occupant didn't make it",
    "Cozy spot near the rats",
    "Great view of absolutely nothing",
    "Only slightly haunted",
    "Comes with free seasickness",
    "Cursed by a sea witch (maybe)",
    "Perfect for hiding from work",
    "Used by Bootstrap Bill himself",
    "Guaranteed nightmares included",
    "The snoring is unbearable here",
    "Leaks when it rains (always rains)",
    "Best seat in the house (it's not)",
    "Formerly owned by a skeleton",
    "Smells like fish. Dead fish.",
    "Great acoustics for screaming",
    "Romantic spot for sword fights",
    "Kraken tested, sailor approved",
    "Conveniently close to the cannon fire",
    "Comes with mysterious stains"
];

const JACK_QUOTES = [
    "Why is the rum always gone?",
    "Not all treasure is silver and gold, mate",
    "Take what you can, give nothing back",
    "The problem is not the problem. The problem is your attitude about the problem",
    "I'm dishonest, and a dishonest man you can always trust to be dishonest",
    "This is the day you will always remember as the day you almost caught Captain Jack Sparrow",
    "I've got a jar of dirt!",
    "But you have heard of me",
    "Savvy?",
    "Close your eyes and pretend it's all a bad dream. That's how I get by",
    "Sea turtles, mate",
    "I love those moments. I like to wave at them as they pass by",
    "Did everyone see that? Because I will not be doing it again",
    "Me? I'm dishonest. And a dishonest man you can always trust to be dishonest",
    "The seas may be rough, but I am the Captain! No matter how difficult, I will always prevail"
];

const PIRATE_NAMES = [
    "Bootstrap Bill",
    "Ragetti",
    "Pintel",
    "Marty",
    "Cotton",
    "Gibbs",
    "Scrum",
    "Murtogg",
    "Mullroy",
    "Scarlett",
    "Giselle",
    "Tia Dalma",
    "Barbossa",
    "Will Turner",
    "Elizabeth Swann"
];